version: '3.7'
services:
  web:
    expose:
      - "8000"
    build: ./
    command: python manage.py runserver
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: .env
    services:
      web:
        tty: true